version: "3.1"

services:
  db:
    image: mariadb
    container_name: Universitiy-Room-Reservation-DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # volumes:
    #   - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
